package com.mycompany.mavenwithdatabase;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class TenantInfo extends javax.swing.JFrame {

    /**
     * Creates new form TenantLog
     */
    public TenantInfo(float waterBill, float electricBill, float roomRent, float maintenanceBill, float totalBilling, String paymentStatus, String dueDate) {
        
        initComponents();

        // Set the data in the JTextAreas
        water.setText(String.valueOf(waterBill));
        electric.setText(String.valueOf(electricBill));
        rent.setText(String.valueOf(roomRent));
        maintain.setText(String.valueOf(maintenanceBill));
        total_bill.setText(String.valueOf(totalBilling));
        payment_m.setText(paymentStatus);
        due_date.setText(dueDate);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        total_bill = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        water = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        electric = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        rent = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        maintain = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        payment_m = new javax.swing.JTextArea();
        BackHome = new javax.swing.JButton();
        VISITORS = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        due_date = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(171, 194, 112));
        setPreferredSize(new java.awt.Dimension(661, 421));

        jPanel3.setBackground(new java.awt.Color(171, 194, 112));
        jPanel3.setPreferredSize(new java.awt.Dimension(661, 50));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BILLING INF0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(477, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(71, 60, 51));
        jLabel1.setText("WATER BILL:");

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(71, 60, 51));
        jLabel3.setText("ELECTRIC BILL:");

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(71, 60, 51));
        jLabel4.setText("MAINTENANCE BILL:");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(71, 60, 51));
        jLabel5.setText("RENT BILL:");

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(71, 60, 51));
        jLabel7.setText("PAYMENT STATUS");

        total_bill.setEditable(false);
        total_bill.setBackground(new java.awt.Color(204, 204, 204));
        total_bill.setColumns(20);
        total_bill.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        total_bill.setForeground(new java.awt.Color(0, 0, 0));
        total_bill.setRows(1);
        total_bill.setTabSize(5);
        total_bill.setBorder(null);
        total_bill.setName("TOTAL"); // NOI18N
        total_bill.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(total_bill);
        total_bill.getAccessibleContext().setAccessibleName("TOTAL");

        water.setEditable(false);
        water.setBackground(new java.awt.Color(204, 204, 204));
        water.setColumns(20);
        water.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        water.setForeground(new java.awt.Color(0, 0, 0));
        water.setRows(1);
        water.setTabSize(5);
        water.setBorder(null);
        water.setName("WATER"); // NOI18N
        water.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(water);
        water.getAccessibleContext().setAccessibleName("WATER");

        electric.setEditable(false);
        electric.setBackground(new java.awt.Color(204, 204, 204));
        electric.setColumns(20);
        electric.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        electric.setForeground(new java.awt.Color(0, 0, 0));
        electric.setRows(1);
        electric.setTabSize(5);
        electric.setBorder(null);
        electric.setName("ELECTRIC"); // NOI18N
        electric.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(electric);
        electric.getAccessibleContext().setAccessibleName("ELECTRIC");

        rent.setEditable(false);
        rent.setBackground(new java.awt.Color(204, 204, 204));
        rent.setColumns(20);
        rent.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        rent.setForeground(new java.awt.Color(0, 0, 0));
        rent.setRows(1);
        rent.setTabSize(5);
        rent.setBorder(null);
        rent.setName("RENT"); // NOI18N
        rent.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(rent);
        rent.getAccessibleContext().setAccessibleName("RENT");

        maintain.setEditable(false);
        maintain.setBackground(new java.awt.Color(204, 204, 204));
        maintain.setColumns(20);
        maintain.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        maintain.setForeground(new java.awt.Color(0, 0, 0));
        maintain.setRows(1);
        maintain.setTabSize(5);
        maintain.setBorder(null);
        maintain.setName("MAINTENANCE"); // NOI18N
        maintain.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane5.setViewportView(maintain);
        maintain.getAccessibleContext().setAccessibleName("MAINTENANCE");

        payment_m.setEditable(false);
        payment_m.setBackground(new java.awt.Color(204, 204, 204));
        payment_m.setColumns(20);
        payment_m.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        payment_m.setForeground(new java.awt.Color(0, 0, 0));
        payment_m.setRows(1);
        payment_m.setTabSize(5);
        payment_m.setBorder(null);
        payment_m.setName("PAYMENTM"); // NOI18N
        payment_m.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane6.setViewportView(payment_m);

        BackHome.setBackground(new java.awt.Color(253, 167, 105));
        BackHome.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        BackHome.setForeground(new java.awt.Color(71, 60, 51));
        BackHome.setText("BACK");
        BackHome.setPreferredSize(new java.awt.Dimension(150, 40));
        BackHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackHomeActionPerformed(evt);
            }
        });

        VISITORS.setBackground(new java.awt.Color(254, 200, 104));
        VISITORS.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        VISITORS.setForeground(new java.awt.Color(71, 60, 51));
        VISITORS.setText("VISITORS");
        VISITORS.setPreferredSize(new java.awt.Dimension(150, 40));
        VISITORS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VISITORSActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(71, 60, 51));
        jLabel2.setText("TOTAL BILL");

        due_date.setEditable(false);
        due_date.setBackground(new java.awt.Color(204, 204, 204));
        due_date.setColumns(20);
        due_date.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        due_date.setForeground(new java.awt.Color(0, 0, 0));
        due_date.setRows(1);
        due_date.setTabSize(5);
        due_date.setBorder(null);
        due_date.setName("PAYMENTM"); // NOI18N
        due_date.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane7.setViewportView(due_date);

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(71, 60, 51));
        jLabel8.setText("DUE DATE:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VISITORS, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BackHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VISITORS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(213, 213, 213))))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VISITORSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VISITORSActionPerformed
        // TODO add your handling code here:
        VisitHistory GoToVisit = new VisitHistory();
        GoToVisit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VISITORSActionPerformed

    private void BackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackHomeActionPerformed
        // TODO add your handling code here:
        Home GoToHome = new Home();
        GoToHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TenantInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TenantInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TenantInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TenantInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TenantInfo(0, 0, 0, 0, 0, "", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackHome;
    private javax.swing.JButton VISITORS;
    private javax.swing.JTextArea due_date;
    private javax.swing.JTextArea electric;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea maintain;
    private javax.swing.JTextArea payment_m;
    private javax.swing.JTextArea rent;
    private javax.swing.JTextArea total_bill;
    private javax.swing.JTextArea water;
    // End of variables declaration//GEN-END:variables
}
